# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="mpthreetest.mp3"
Content-Type: audio/mpeg

< ./mpthreetest.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription
POST http://localhost:3333/videos/aa31eeda-b78a-4735-a723-34a34f9f589b/transcription
Content-Type: application/json

{
  "prompt": "The Impostor Syndrome"
}

###

# @name generate-ai-completion
POST http://localhost:3333/ai/complete
Content-Type: application/json

{
  "videoId": "aa31eeda-b78a-4735-a723-34a34f9f589b",
  "temperature": 0.5,
  "template": "Gere um resumo sucinto da transcrição do vídeo informada a seguir: '''{transcription}'''"
}